# Generated by Django 4.2.3 on 2024-02-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_address_rename_phone_number_contact_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
    ]
